import 'package:equatable/equatable.dart';

/// generate by https://javiercbk.github.io/json_to_dart/
class AutogeneratedOSLyricHouse {
  final List<OSLyricHouseModel> results;

  AutogeneratedOSLyricHouse({required this.results});

  factory AutogeneratedOSLyricHouse.fromJson(Map<String, dynamic> json) {
    var temp = <YouAwesomeModel>[];
    if (json['results'] != null) {
      temp = <OSLyricHouseModel>[];
      json['results'].forEach((v) {
        temp.add(OSLyricHouseModel.fromJson(v as Map<String, dynamic>));
      });
    }
    return AutogeneratedOSLyricHouse(results: temp);
  }

  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['results'] = results.map((v) => v.toJson()).toList();
    return data;
  }
}

class OSLyricHouseModel extends Equatable {
  final int id;
  final String name;

  OSLyricHouseModel(this.id, this.name);

  @override
  List<Object> get props => [id, name];

  factory OSLyricHouseModel.fromJson(Map<String, dynamic> json) {
    return OSLyricHouseModel(json['id'] as int, json['name'] as String);
  }

  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['id'] = id;
    data['name'] = name;
    return data;
  }
  
}
